### ISSUE TITLE
ZhipuAI(api_key=os.getenv("ZHIPUAI_API_KEY")) 

### ISSUE THREAD

**Issue by hgsw** [datawhalechina/tiny-universe#10]
你好，非常感谢这么好的一个学习仓库

我在学习Tiny-RAGd的时候，已经在autodl远程服务器上部署了InternLM2-chat-7B的LLM模型
之后我在学习步骤6. LLM Tiny-RAG Demo创建zhipu的embedding对象时，需要从环境变量中加载 ZHIPUAI_API_KEY ，请问我该如何获取这个值呢？

报错信息如下：
![图片](https://github.com/datawhalechina/tiny-universe/assets/51161001/b7b5169d-238c-4da7-a178-950db26c48dc)

**Comment by hgsw** [comment]
已经解决
在https://open.bigmodel.cn/overview注册智谱AI开放平台即可获取

**Comment by ZhongQiyu** [comment]
加载到环境变量，这个从HuggingFace也能接API获取
