### ISSUE TITLE
一点笔误哈

### ISSUE THREAD

**Issue by stay-leave** [datawhalechina/tiny-universe#13]
在 Transformer 的 Decoder 结构中，Q 来自于 Encoder 的输出，K 与 V 来自于 Decoder 的输入
写反了

**Comment by Yewx0310** [comment]
我也发现了，刚想提issue

**Comment by logan-zou** [comment]
![image](https://github.com/datawhalechina/tiny-universe/assets/74288839/e8067dbd-96cb-4831-9a3f-21e7bc985a5d)
您好，参考原论文，确实是 Q 来自于 Decoder 的输入，K 和 V 来自于 Encoder 的输出哈

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.

**Comment by Yewx0310** [comment]
> ![image](https://private-user-images.githubusercontent.com/74288839/333845675-e8067dbd-96cb-4831-9a3f-21e7bc985a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTQ2MTgsIm5iZiI6MTcxNjY5NDMxOCwicGF0aCI6Ii83NDI4ODgzOS8zMzM4NDU2NzUtZTgwNjdkYmQtOTZjYi00ODMxLTlhM2YtMjFlN2JjOTg1YTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDAzMzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NTJkYmFjNTA2N2QxZTEzODMyOWNiZmI0NDgzMGU3YTg3ZGNkNWUxNzhmNDU2OWQ5NzlkNTgwNTI5MGVjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uIXzEZAoRVx2aew-MptfaaaSjmQ77Nc3bNYQ_1VBgY) 您好，参考原论文，确实是 Q 来自于 Decoder 的输入，K 和 V 来自于 Encoder 的输出哈

是的，但是您在写的时候写错了，具体参见TinyTransformer中的这个部分
![Uploading 1716694307630.png…]()

**Comment by Yewx0310** [comment]
是的，但是您在写的时候写错了，具体参见TinyTransformer中的这个部分
![1716694307630](https://github.com/datawhalechina/tiny-universe/assets/96856049/85f5be1e-fa63-4321-8648-62a724509b00)

**Comment by Yewx0310** [comment]
> ![image](https://private-user-images.githubusercontent.com/74288839/333845675-e8067dbd-96cb-4831-9a3f-21e7bc985a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTQ3NjIsIm5iZiI6MTcxNjY5NDQ2MiwicGF0aCI6Ii83NDI4ODgzOS8zMzM4NDU2NzUtZTgwNjdkYmQtOTZjYi00ODMxLTlhM2YtMjFlN2JjOTg1YTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDAzMzQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNmE4YTU3NDE1NTM2ODc2YTVkNjk5MzAyOTI5MjNmZmU5MGI3N2MzM2FhYjI5YTViZDkxZGVkMDM2ZDg5YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a8kxI46O9CvH7fJWK8jrd367yFmLzi3o1CYpaT8aQRU) 您好，参考原论文，确实是 Q 来自于 Decoder 的输入，K 和 V 来自于 Encoder 的输出哈

是的，但是您在写的时候写错了，具体参见TinyTransformer中的这个部分
![1716694307630](https://github.com/datawhalechina/tiny-universe/assets/96856049/4f7a3478-af43-4ccc-93a3-e1d47b198206)

**Comment by logan-zou** [comment]
已修正，感谢提醒
