### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cl-27** [datawhalechina/tiny-universe#16]
up主，能help讲一下怎么样才能对word，excel还有json格式文件处理能？还有大模型能换成百川应该怎么修改啊？代码应该怎么改啊？还有这种方式的检索速度很慢，怎么样才可以在这个代码的基础上去提高检索速度能？

**Comment by Hongru0306** [comment]
本次的课程不涉及具体其他模型的微调哈，可以移步到self-llm项目。
