### ISSUE TITLE
[Bug] Qwen-blog的小bug

### ISSUE THREAD

**Issue by ThousandLayerCake** [datawhalechina/tiny-universe#21]
在1.3.3.1 GQA中，关于代码
```python
#(bs, head, seq_len, head_dim)
query = query.transpose(1, 2)
key = repeat_kv(key, 4).transpose(1, 2)
value = repeat_kv(value, 4).transpose(1, 2)
scores = torch.matmul(query, key.transpose(2, 3)) / math.sqrt(head_dim)
```
转置的位置写错了，应该先转置再传入`repeat_kv()` ? 
```python
#(bs, head, seq_len, head_dim)
query = query.transpose(1, 2)
key = repeat_kv(key.transpose(1, 2), 4)
value = repeat_kv(value.transpose(1, 2), 4)
scores = torch.matmul(query, key.transpose(2, 3)) / math.sqrt(head_dim)
```

另外，感谢作者提供这么好的教程！

**Comment by Hongru0306** [comment]
> 在1.3.3.1 GQA中，关于代码
> 
> ```python
> #(bs, head, seq_len, head_dim)
> query = query.transpose(1, 2)
> key = repeat_kv(key, 4).transpose(1, 2)
> value = repeat_kv(value, 4).transpose(1, 2)
> scores = torch.matmul(query, key.transpose(2, 3)) / math.sqrt(head_dim)
> ```
> 
> 转置的位置写错了，应该先转置再传入`repeat_kv()` ?
> 
> ```python
> #(bs, head, seq_len, head_dim)
> query = query.transpose(1, 2)
> key = repeat_kv(key.transpose(1, 2), 4)
> value = repeat_kv(value.transpose(1, 2), 4)
> scores = torch.matmul(query, key.transpose(2, 3)) / math.sqrt(head_dim)
> ```
> 
> 另外，感谢作者提供这么好的教程！

ok，感谢指正，感谢支持
