### ISSUE TITLE
求更新tinyllama的tokenizer

### ISSUE THREAD

**Issue by Jse-NGV** [datawhalechina/tiny-universe#22]
这个系列做的很不错，动手from scratch的过程学到了很多，希望tinyllama能更新一下tokenzier部分

**Comment by Hongru0306** [comment]
> 这个系列做的很不错，动手from scratch的过程学到了很多，希望tinyllama能更新一下tokenzier部分

感谢认可！！最近在疯狂赶稿ddl，争取月底组队学习时发布！！
