### ISSUE TITLE
Problems with picture display

### ISSUE THREAD

**Issue by acwwt** [datawhalechina/tiny-universe#8]
葱佬这个图片显示有问题，仓库中没找到，修改一下吧
![image](https://github.com/datawhalechina/tiny-universe/assets/110531742/aacb0bf4-b55b-4ebd-b477-c544dc7a744b)

**Comment by Hongru0306** [comment]
> 葱佬这个图片显示有问题，仓库中没找到，修改一下吧 ![image](https://private-user-images.githubusercontent.com/110531742/328743947-aacb0bf4-b55b-4ebd-b477-c544dc7a744b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjU3NTMsIm5iZiI6MTcxNTE2NTQ1MywicGF0aCI6Ii8xMTA1MzE3NDIvMzI4NzQzOTQ3LWFhY2IwYmY0LWI1NWItNGViZC1iNDc3LWM1NDRkYzdhNzQ0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQxMDUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmM3OTZlMDAxNzM2ODA2NGJiNGEyZjE1OTY2Y2ViOGFmODgwNjE0OGViMWQ3ZWNkNGY5ODkwMzc3NTliMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YHaMD0lwpHYrxG3Om9gsXwMdcZDKorg3eBd-ydDVg-M)

好的，感谢指出！
